name: test-boot
description: 'Process test bootstrap build by OW (for test compatibility)'
inputs:
  hostos:
    description: 'host os'
    required: false
    default: ''
    type: string
  owdebug:
    description: 'verbosed/debug output for GH Actions scripts development'
    required: false
    default: ''
    type: string
  testboot:
    description: 'if test boot with new OW version'
    required: false
    default: ''
    type: string
  testmode:
    description: 'testing mode (no build)'
    required: false
    default: ''
    type: string
runs:
  using: composite
  steps:
  - if: inputs.hostos == 'lnx'
    name: Test Bootstrap OW
    run: |
      if [ "${{ inputs.owdebug }}" = "1" ]; then
        env | sort
      fi
      if [ "${{ inputs.testmode }}" = "" ]; then
        ci/buildx.sh
      fi
    env:
      OWBUILD_STAGE: 'boot'
      OWTOOLS:       'WATCOM'
      OWROOT:        ${{ github.workspace }}
      OWDEBUG:       ${{ inputs.owdebug }}
      OWVERBOSE:     1
      TESTBOOT:      ${{ inputs.testboot }}
    shell: bash
  - if: inputs.hostos == 'nt'
    name: Test Bootstrap OW
    run: |
      if "${{ inputs.owdebug }}" == "1" (
        set
      )
      if "${{ inputs.testmode }}" == "" (
        ci\buildx.cmd
      )
    env:
      OWBUILD_STAGE: 'boot'
      OWTOOLS:       'WATCOM'
      OWROOT:        ${{ github.workspace }}
      OWDEBUG:       ${{ inputs.owdebug }}
      OWVERBOSE:     1
      TESTBOOT:      ${{ inputs.testboot }}
    shell: cmd
