name: CI-Build-nt
run-name: CI workflow Windows
on:
  workflow_call:
    inputs:
      arch:
        required: true
        type: string
      tools:
        required: true
        type: string
      owtools:
        required: true
        type: string
      image:
        required: true
        type: string

jobs:
  boot-nt:
    name: Bootstrap
    runs-on: ${{ inputs.image }}

    steps:
    - name: Set git EOL to LF
      run: |
        git config --global core.eol lf
        git config --global core.autocrlf input
    - name: checkout
      uses: actions/checkout@v4
    - name: Bootstrap
      uses: "./.github/actions/boot"
      with:
        args:       ${{ inputs.tools }}
        suffix:     "nt ${{ inputs.arch }} ${{ inputs.tools }}"
        owtools:    ${{ inputs.owtools }}
        owdebug:    ${{ vars.OWDEBUG }}

  build-nt:
    name: Build
    needs: boot-nt
    runs-on: ${{ inputs.image }}
    timeout-minutes: 120

    steps:
    - name: Set git EOL to LF
      run: |
        git config --global core.eol lf
        git config --global core.autocrlf input
    - name: checkout
      uses: actions/checkout@v4
    - name: Install DOSBOX
      uses: "./.github/actions/dosboxin"
    - name: Build
      uses: "./.github/actions/build"
      with:
        args:       ${{ inputs.tools }}
        suffix:     "nt ${{ inputs.arch }} ${{ inputs.tools }}"
        owtools:    ${{ inputs.owtools }}
        owdebug:    ${{ vars.OWDEBUG }}
        testmode:   ${{ vars.TESTMODE }}

  docsbuild:
    name: Docs Build
    needs: boot-nt
    timeout-minutes: 90
    strategy:
      matrix:
        include:
        - title: DOS
          doctype: docdos
        - title: OS/2
          doctype: docos2
        - title: NT
          doctype: docnt
        - title: CHM
          doctype: docchm
        - title: PDF
          doctype: docpdf
        - title: WIN
          doctype: docwin
    runs-on: ${{ inputs.image }}

    steps:
    - name: Set git EOL to LF
      run: |
        git config --global core.eol lf
        git config --global core.autocrlf input
    - name: checkout
      uses: actions/checkout@v4
    - name: Install DOSBOX
      uses: "./.github/actions/dosboxin"
    - name: Build
      uses: "./.github/actions/docbuild"
      with:
        args:       ${{ inputs.tools }}
        target:     ${{ matrix.doctype }}
        suffix:     "nt ${{ inputs.arch }} ${{ inputs.tools }}"
        doc_suffix: "${{ matrix.doctype }} ${{ inputs.tools }}"
        owtools:    ${{ inputs.owtools }}
        owdebug:    ${{ vars.OWDEBUG }}
        testmode:   ${{ vars.TESTMODE }}

  tests-nt:
    if: inputs.arch == 'x64'
    needs: build-nt
    name: Tests
    uses: "./.github/workflows/tests.yml"
    with:
      suffix: "nt ${{ inputs.arch }} ${{ inputs.tools }}"
      image:  ${{ inputs.image }}
