name: Release-Build-lnx
run-name: Release workflow Linux (daily and monthly)
on:
  workflow_call:
    inputs:
      arch:
        required: true
        type: string
      tools:
        required: true
        type: string
      owtools:
        required: true
        type: string
      image:
        required: true
        type: string
jobs:
  boot-lnx:
    name: Bootstrap
    runs-on: ${{ inputs.image }}
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Bootstrap
      uses: "./.github/actions/boot"
      with:
        args:       ${{ inputs.tools }}
        suffix:     "lnx ${{ inputs.arch }} ${{ inputs.tools }}"
        owtools:    ${{ inputs.owtools }}
        owdebug:    ${{ vars.OWDEBUG }}
  build-lnx:
    needs: boot-lnx
    name: Build
    runs-on: ${{ inputs.image }}
    timeout-minutes: 120
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Install DOSBOX
      uses: "./.github/actions/dosboxin"
    - name: Build
      uses: "./.github/actions/build"
      with:
        args:       ${{ inputs.tools }}
        suffix:     "lnx ${{ inputs.arch }} ${{ inputs.tools }}"
        owtools:    ${{ inputs.owtools }}
        owdebug:    ${{ vars.OWDEBUG }}
        testmode:   ${{ vars.TESTMODE }}
  tests-lnx:
    name: Tests
    if: inputs.arch == 'x64'
    needs: build-lnx
    uses: ./.github/workflows/tests.yml
    with:
      suffix:   "lnx ${{ inputs.arch }} ${{ inputs.tools }}"
      image:    ${{ inputs.image }}
